# Generated by Django 3.1.4 on 2021-01-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_manager', '0004_auto_20201230_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Add Order', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='my_field_name',
            field=models.CharField(help_text='Enter product description', max_length=40),
        ),
    ]
