# Generated by Django 3.1.4 on 2021-01-21 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_manager', '0009_order_app_fee_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraiser',
            name='fee_split_rate',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='appraiser',
            name='insurance_exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 13, 21, 15, 150962)),
        ),
        migrations.AddField(
            model_name='appraiser',
            name='sick_days_start',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='appraiser',
            name='sick_days_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appraiser',
            name='status',
            field=models.CharField(default='Active', max_length=15),
        ),
        migrations.AddField(
            model_name='appraiser',
            name='vacation_days_start',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='appraiser',
            name='vacation_days_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='last_ordered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 13, 21, 15, 151960)),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
