# Generated by Django 3.1.4 on 2021-01-22 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_manager', '0011_auto_20210121_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraiser',
            name='f_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appraiser',
            name='l_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appraiser',
            name='insurance_exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 16, 32, 33, 993747)),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_ordered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 16, 32, 33, 993747)),
        ),
    ]
