# Generated by Django 3.1.4 on 2021-01-22 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_manager', '0017_auto_20210121_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraiser',
            name='insurance_exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 22, 16, 57, 8, 5003)),
        ),
        migrations.AlterField(
            model_name='appraiser',
            name='license_exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 22, 16, 57, 8, 4976)),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_ordered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 22, 16, 57, 8, 5872)),
        ),
    ]
