# Generated by Django 3.1.4 on 2021-02-04 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_manager', '0020_auto_20210204_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraiser',
            name='insurance_exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 4, 9, 27, 35, 853520)),
        ),
        migrations.AlterField(
            model_name='appraiser',
            name='license_exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 4, 9, 27, 35, 853491)),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_ordered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 4, 9, 27, 35, 854234)),
        ),
    ]
