# Generated by Django 3.1.4 on 2020-12-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appraiser',
            options={'ordering': ['-my_field_name']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-my_field_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-my_field_name']},
        ),
        migrations.AddField(
            model_name='appraiser',
            name='my_field_name',
            field=models.CharField(help_text='Enter appraiser name', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='my_field_name',
            field=models.CharField(help_text='Enter client name', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='my_field_name',
            field=models.CharField(help_text='Enter product description', max_length=20, null=True),
        ),
    ]
