# Generated by Django 3.1.4 on 2020-12-31 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('office_manager', '0003_auto_20201230_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-my_field_name']},
        ),
        migrations.AddField(
            model_name='user',
            name='my_field_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Enter user name', max_length=20),
            preserve_default=False,
        ),
    ]
