# Generated by Django 3.1.4 on 2021-01-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_manager', '0006_auto_20210109_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
    ]
