# Generated by Django 3.1.4 on 2021-01-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_manager', '0007_remove_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraiser',
            name='capacity',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
