# Generated by Django 3.1.4 on 2021-01-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_manager', '0008_appraiser_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='app_fee_split',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
